name: Python Benchmark

on:
  pull_request:

concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./bindings/python
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.10"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/setup.cfg'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # 1.12.1
        with:
          mongodb-version: 6.0
      - name: Install deps
        run: |
          python -m pip install rust-just uv
      - name: Set up env
        run: |
           set -eux
           echo "LIBBSON_INSTALL_DIR=$PWD/libbson" >> $GITHUB_ENV
           git fetch origin $GITHUB_BASE_REF:base_branch
           git fetch origin $GITHUB_REF:head_branch
      - name: Install libbson
        run: |
          just build-libbson
      - name: Install benchmarks
        run: |
          just benchmark-install
      - name: Run benchmarks
        run: |
          just benchmark base_branch..head_branch
      - name: Compare benchmarks
        run: |
          .venv/bin/asv compare --factor 1.2 --split head_branch base_branch --

      - name: Fail if any benchmarks have slowed down too much
        run: |
          .venv/bin/asv compare --factor 1.2 --split head_branch base_branch 2> /dev/null | grep -q "got worse"
